export const voices = {
    subtitles:{
      graduationPhotos:{
        view:["Text1","Text2","Text3"]
      },
      keys:{
        view:["Text1"],
        get:["Text1"]
      }
    },
    audios:{
      graduationPhotos:{
        view:["Path1","Path2","Path3"]
      },
      keys:{
        view:["Path1"],
        get:["Path1"]
      }
    }
}